/**
 * JWT is a way to authenticate and authorize users
 * 
 * 1. User logs in with username and password
 * 2. Server validates credentials and returns a JWT
 * 3. Client stores JWT in localStorage or session storage
 * 4. Client sends JWT in Authorization header for protected routes
 * 5. Server validates JWT and allows access to protected route
 * 
 * It will remain stateless and secure
 * 
 */

const jwt = require('jsonwebtoken');
/**
 * Secret key for signing and verifying JWT
 * Should be stored in environment variables
 */

const secretKey = process.env.JWT_SECRET_KEY;
const JWT_EXPIRATION = '7d';

if (!secretKey) {
    throw new Error('JWT_SECRET_KEY is not set in environment variables');
}

/**
 * Will generate a JWT token for a user
 * 
 * @param {Object} user - The user object to generate a token for
 * @returns {string} - Signed JWT token
 * 
 * The token recieves:
 * - user id
 * - username
 * - issued at timestamp (autogenerated)
 * - expiration timestamp (autogenerated)
 * 
 * TODO: Add refresh token capability for better security
 * TODO: Include role-based access control in payload
 */
function generateToken(user) {
    // Passwords and other sensitive data are not included in the token
    const payload = {
        id: user.id,
        username: user.username,
    };

    const token = jwt.sign(payload, secretKey, { expiresIn: JWT_EXPIRATION });

    return token;
}

/**
 * Verify and decode a JWT token
 * 
 * @param {string} token - The JWT token to verify and decode
 * @returns {Object} - Decoded payload object or null if token is invalid
 * 
 * The function does the following:
 *  - Checks if the token signature is valid
 *  - Checks if the token has expired
 *  - Returns the decoded payload object if everything is valid
 * 
 * TODO: Add token blacklisting for logged out users
 * TODO: Validate payload structure and data types
 */
function verifyToken(token) {
    // JWT verify will throw an error if the token is invalid, which we will catch and return null
    try {
        const decoded = jwt.verify(token, secretKey);
        return decoded;
    } catch (error) {
        if (error.name === 'TokenExpiredError') {
            console.log("Token expired:", error.message);
        } else if (error.name === 'JsonWebTokenError') {
            console.log("Invalid token:", error.message);
        } else {
            console.log("Error verifying token:", error.message);
        }
        return null;
    }
}

/**
 * Extract token from Authorization header
 * 
 * Expected format: "Bearer <token>"
 * Example "Bearer 1234567890"
 * 
 * @param {Object} authHeader - The Authorization header to extract the token from
 * @returns {string|null} - The token if it is valid, null if it is invalid
 */
function extractTokenFromHeader(authHeader) {
    if (!authHeader) {
        return null;
    }
    // If it doesnt start with "Bearer "
    if (!authHeader.startsWith('Bearer ')) {
        return null;
    }
    // Extract the token
    return authHeader.split(' ')[1];
}

/**
 * Middleware to authenticate requests
 * Will be used in Express routes to protect endpoints
 * 
 * @param {Object} req - The request object
 * @param {Object} res - The response object
 * @param {Function} next - The next function to call
 */
function authenticateToken(req, res, next) {
    // Get the token from the Authorization header
    const authHeader = req.headers['authorization'];
    const token = extractTokenFromHeader(authHeader);

    if (!token) {
        return res.status(401).json({
            error: 'Access was denied, no token provided.'
        });
    }
    // Verify the token
    const decoded = verifyToken(token);

    if (!decoded) {
        return res.status(401).json({
            error: 'Invalid or expired token.'
        });
    }
    // Attach the user data to the request object
    req.user = decoded;

    // Continue to the next middleware or route handler
    next();
}

/**
 * Optional middleware - Wont fail if token is not provided
 * Going to use it for routes that are not protected
 * This will be good for routes that behave differently if a user is authenticated or not
 * 
 * Examples: Personalized results page, show position on leaderboard, post viewing, etc...
 * 
 * @param {Object} req - The request object
 * @param {Object} res - The response object
 * @param {Function} next - The next function to call
 */
function optionalAuth(req, res, next) {
    const authHeader = req.headers['authorization'];
    const token = extractTokenFromHeader(authHeader);

    if (token) {
        const decoded = verifyToken(token);
        if (decoded) {
            req.user = decoded;
        }
    }
    next();
}




module.exports = {
    generateToken,
    verifyToken,
    extractTokenFromHeader,
    authenticateToken,
    optionalAuth,
};